# Generated by Django 4.1.7 on 2023-03-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicfile',
            name='audio_length',
            field=models.FloatField(default=None, null=True),
        ),
    ]
